apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot-app
          image: lahham666/freightous-task  # Replace with your actual image tag
          envfrom:
            - configMapRef:
                name: db-config 
          ports:
            - containerPort: 8080  # Assuming the Spring Boot app runs on port 8080
      imagePullSecrets:
        - name: docker-cred  # Secret for pulling from DockerHub

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
spec:
  selector:
    app: springboot
  ports:
    - protocol: TCP
      port: 80       # Expose the service on port 80
      targetPort: 8080  # Map it to the container's port 8080
  type: NodePort  # Use NodePort for Minikube instead of LoadBalancer
